<?php

namespace AppBundle\Repository;

/**
 * TachesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TachesRepository extends \Doctrine\ORM\EntityRepository
{
}
